name: "Publish package: @exile-watch / doryani"

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  issues: write
  packages: write

jobs:
  code-quality-assurance:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to GitHub Registry
        uses: exile-watch/doryani/auth-github-registry@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Code quality assurance
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        uses: exile-watch/doryani/code-quality-assurance@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build
        run: npm run build
        shell: bash

  publish-package:
    needs: [code-quality-assurance]
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node

      - name: Authenticate to GitHub Registry
        uses: exile-watch/doryani/auth-github-registry@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}

      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}

      - name: Build package
        run: npm run build
        if: ${{ steps.release.outputs.release_created }}

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}