name: "Publish package: @exile-watch / doryani"

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  auth-github-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to GitHub Registry
        uses: exile-watch/doryani/auth-github-registry@main
        with:
          GH_TOKEN: ${{ inputs.GH_TOKEN }}
          GH_ACTOR: ${{ inputs.GH_ACTOR }}

  publish-package:
    needs: [auth-github-registry]
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@exile-watch'
        if: ${{ steps.release.outputs.release_created }}
      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}